name: "X is to Y API CI"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
    uv_lock:
        name: uv Lock Sync
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/install_uv
            - run: uv lock --locked # check uv lock file in sync with toml

    lint:
        name: Lint with Ruff
        runs-on: ubuntu-latest
        needs: [uv_lock] # https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idneeds

        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/install_uv
            - run: uvx ruff check .

    format:
        name: Format with Ruff
        runs-on: ubuntu-latest
        needs: [uv_lock]

        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/install_uv
            - run: uvx ruff format --check . # run without --check to reformat

    import_sort:
        name: Sort imports with isort
        runs-on: ubuntu-latest
        needs: [uv_lock]

        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/install_uv
            - run: uvx isort .

    type_check:
        name: Check type hints with mypy
        runs-on: ubuntu-latest
        needs: [uv_lock]

        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions/install_uv
            - run: uvx mypy .